# environment.prod.yml
name: gnn-fastapi-prod
channels:
  - conda-forge
  - defaults
pip-repositories:
  - https://download.pytorch.org/whl/cpu
dependencies:
  - python=3.12
  - fastapi
  - pydantic
  - uvicorn
  - pip
  - rdkit
  - scipy
  - pandas
  - numpy
  - pip:
    # - --extra-index-url https://download.pytorch.org/whl/cpu
    - torch==2.10.0
    - torch-geometric==2.7.0
    - datamol
    - selfies
    - py3dmol
    - tqdm
    - loguru