# environment.prod.yml
name: gnn-fastapi-prod
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - fastapi
  - pydantic
  - uvicorn
  - pip
  - rdkit
  - scipy
  - pandas
  - numpy